import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import ReactMarkdown from 'react-markdown'
import { useEffect, useRef, useState } from 'react'
import Float from '@/components/float'
const random1 = Math.random() * 1000
const random2 = Math.random() * 1000
export default function Home () {
  const scrll = () => window.scrollTo({
    top: document.documentElement.scrollHeight,
    behavior: 'smooth'
  })
  const refPre = useRef()
  const refKey = useRef()
  const [key, setKey] = useState('')
  const [conversation, setConversation] = useState([{ role: 'system', content: 'Eres una inteligencia artificial.' }])
  const [esp, setEsp] = useState('')
  useEffect(() => {
    setKey(localStorage.getItem('key'))
  }, [key, setKey])
  async function handleSubmit (e) {
    e.preventDefault()
    const pregunta = refPre.current.value
    scrll()
    if (pregunta && key) {
      setEsp('Generando respuesta')
      const conver = [...conversation, { role: 'user', content: pregunta }]
      setConversation(conver)
      refPre.current.value = ''
      const res = await fetch('/api', {
        method: 'POST',
        headers: {
          'Content-type': 'application/json'
        },
        body: JSON.stringify({ conver, key })
      })
      res.json().then((result) => {
        const resultado = result.result[0].message.content
        setConversation([...conver, { role: 'assistant', content: resultado }])
      }
      )
      setEsp('')
      scrll()
    } else {
      alert('Introduce una pregunta')
    }
    scrll()
  }
  function handleKey (e) {
    e.preventDefault()
    const valorKey = refKey.current.value
    if (valorKey) {
      setKey(valorKey)
      localStorage.setItem('key', valorKey)
    } else {
      alert('introduce la api key')
    }
  }
  return (
    <>
      <Head>
        <title>CReal-GPT</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Float />
        <form className={styles.pregunta} style={{ '--display': key ? 'flex' : 'none' }} onSubmit={(e) => handleSubmit(e)}>
          <input placeholder='Mensaje' ref={refPre} />
          <button>Enviar</button>
        </form>

        <ul className={styles.ul}>
          {
            conversation.length > 1
              ? (
                  conversation.map((rp, i) => {
                    let st
                    let random
                    let envelope
                    if (rp.role === 'user') {
                      st = styles.user
                      random = key ?? random1
                      envelope = (child) => child
                    } else if (rp.role === 'assistant') {
                      st = styles.ai
                      random = random2
                      envelope = (child) => {
                        return (
                          <ReactMarkdown>
                            {child}
                          </ReactMarkdown>
                        )
                      }
                    } else {
                      st = styles.sys
                      envelope = (child) => child
                    }
                    return (
                      <li
                        className={st}
                        style={{ '--url': `url('https://api.dicebear.com/5.x/adventurer/svg?seed=${random}')` }}
                        key={i}
                      >

                        {
                          envelope(rp.content)
                        }
                      </li>
                    )
                  })
                )
              : (
                <li className={styles.nada}>
                  <h2>¿Qué necesitas?</h2>
                  <p>
                    Soy una IA muy sabia, una de las más capaces del mercado.
                  </p>
                  <h3>Esta IA puede:</h3>
                  <ul>
                    <li>Tener una variedad de aplicaciones, ya que interactuo con los usuarios en
                      tiempo real y ofrezco una experiencia de conversación más natural.
                    </li>
                    <li>Ser utilizada para proporcionar información y asistencia en tiempo real a los estudiantes,
                      responder preguntas sobre cursos y asignaciones, y ofrecer recomendaciones personalizadas para el aprendizaje.
                    </li>
                    <li>Proporcionar soluciones a problemas técnicos y asistir en la resolución de problemas de manera rápida y eficiente.</li>
                  </ul>
                  <p>¿Necesitas reiniciar la conversación? Reinicia la página 😅</p>
                  <p>
                    ¿Mis limitaciones? Descúbrelas por ti mismo 😎
                  </p>
                  <form className={styles.keyform} style={{ '--display': key ? 'none' : 'flex' }} onSubmit={(e) => handleKey(e)}>
                    <input placeholder='api key de OpenAi' ref={refKey} />
                    <button>
                      Empezar
                    </button>
                  </form>
                </li>
                )

          }
        </ul>
        <p className={styles.mess}>
          {esp}
        </p>
      </main>
    </>
  )
}
